### ISSUE TITLE
Sparse checkout with patterns suddenly stopped working

### ISSUE THREAD

**Issue by karimbahgat** [snow-actions/sparse-checkout#34]
Hi, I have a Github Action that previously successfully (last run was April 2022) used this action as follows:

```
jobs:
  # This workflow contains a single job named "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    # Each step runs a single command using the runners shell
    steps:
    - name: Sparse checkout action
      uses: snow-actions/sparse-checkout@v1.1.0
      with: 
        patterns: |
          buildData
          releaseData
          topojson_simple
          !*.zip
```

With no changes on my side when I tried running it now, it suddenly resulted in the following error during "Setting up sparse action":
```
fatal: specify directories rather than patterns.  If your directory starts with a '!', pass --skip-checks
```

I understand that this likely has to do with my use of patterns and that this action likely uses cone mode which doesn't allow patterns, but I don't understand how that can be since the very same setup has worked previously, and it's even pinned to the v1.1.0 release. My code is even following the readme example exactly. I've tried to update to v1.2.0, and fixing the ubuntu version to the previous one 20.04, but still same error. 

Any thoughts on what's happened? Or suggestions for fixes?
